services:
  nestjs_api_prod:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - PORT=3001
      - NODE_ENV=production
    volumes:
      - ./src:/usr/server/src/app
