version: "3"

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=somedb
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password123

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - VITE_REACT_APP_API_ENDPOINT=/api

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: somedb
    ports:
      - "5432:5432"
